//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumPad {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GumPad.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2007 Pradyumna Kumar Revur. All rights reserved.
        /// 
        ///GumPad is freeware. You may use it at your own risk for any purpose you like. You may redistribute GumPad in source or binary form with or without modification, provided that redistributions reproduce the above copyright notice, this statement of conditions, the following disclaimer and an acknowledgement in the documentation and/or other materials provided with the distribution. Neither the name GumPad nor the name of Pradyumna Kumar Revur or [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LicenseFile {
            get {
                return ResourceManager.GetString("LicenseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fswiss\fcharset0 Arial;}}
        ///{\*\generator Msftedit 5.41.21.2507;}\viewkind4\uc1\pard\qc\f0\fs44 Quick Start Guide\par
        ///\pard\fs20\par
        ///GumPad is an easy to use editor for composing text in Indian languages. It works almost like notepad for editing text. To compose text in one of the supported Indian langauges, you will need to type text in English almost like how we spell most Indian names and words in English. For e.g., to compose the word himalaya in a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuickStart {
            get {
                return ResourceManager.GetString("QuickStart", resourceCulture);
            }
        }
    }
}
