//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class ITRANS : global::System.Configuration.ApplicationSettingsBase {
        
        private static ITRANS defaultInstance = ((ITRANS)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ITRANS())));
        
        public static ITRANS Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".N")]
        public string T00100_SIGN_CANDRABINDU {
            get {
                return ((string)(this["T00100_SIGN_CANDRABINDU"]));
            }
            set {
                this["T00100_SIGN_CANDRABINDU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".m,.n,M")]
        public string T00200_SIGN_ANUSVARA {
            get {
                return ((string)(this["T00200_SIGN_ANUSVARA"]));
            }
            set {
                this["T00200_SIGN_ANUSVARA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string T00300_SIGN_VISARGA {
            get {
                return ((string)(this["T00300_SIGN_VISARGA"]));
            }
            set {
                this["T00300_SIGN_VISARGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a")]
        public string T00400_LETTER_A {
            get {
                return ((string)(this["T00400_LETTER_A"]));
            }
            set {
                this["T00400_LETTER_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aa,A")]
        public string T00500_LETTER_AA {
            get {
                return ((string)(this["T00500_LETTER_AA"]));
            }
            set {
                this["T00500_LETTER_AA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i")]
        public string T00600_LETTER_I {
            get {
                return ((string)(this["T00600_LETTER_I"]));
            }
            set {
                this["T00600_LETTER_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ii,I")]
        public string T00700_LETTER_II {
            get {
                return ((string)(this["T00700_LETTER_II"]));
            }
            set {
                this["T00700_LETTER_II"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u")]
        public string T00800_LETTER_U {
            get {
                return ((string)(this["T00800_LETTER_U"]));
            }
            set {
                this["T00800_LETTER_U"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uu,U")]
        public string T00900_LETTER_UU {
            get {
                return ((string)(this["T00900_LETTER_UU"]));
            }
            set {
                this["T00900_LETTER_UU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R^i,RRi")]
        public string T01000_LETTER_VOCALIC_R {
            get {
                return ((string)(this["T01000_LETTER_VOCALIC_R"]));
            }
            set {
                this["T01000_LETTER_VOCALIC_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L^i,LLi")]
        public string T01100_LETTER_VOCALIC_L {
            get {
                return ((string)(this["T01100_LETTER_VOCALIC_L"]));
            }
            set {
                this["T01100_LETTER_VOCALIC_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string T01200_LETTER_E {
            get {
                return ((string)(this["T01200_LETTER_E"]));
            }
            set {
                this["T01200_LETTER_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e")]
        public string T01300_LETTER_EE {
            get {
                return ((string)(this["T01300_LETTER_EE"]));
            }
            set {
                this["T01300_LETTER_EE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ai")]
        public string T01400_LETTER_AI {
            get {
                return ((string)(this["T01400_LETTER_AI"]));
            }
            set {
                this["T01400_LETTER_AI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("O")]
        public string T01500_LETTER_O {
            get {
                return ((string)(this["T01500_LETTER_O"]));
            }
            set {
                this["T01500_LETTER_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("o")]
        public string T01600_LETTER_OO {
            get {
                return ((string)(this["T01600_LETTER_OO"]));
            }
            set {
                this["T01600_LETTER_OO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au")]
        public string T01700_LETTER_AU {
            get {
                return ((string)(this["T01700_LETTER_AU"]));
            }
            set {
                this["T01700_LETTER_AU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("k")]
        public string T01800_LETTER_KA {
            get {
                return ((string)(this["T01800_LETTER_KA"]));
            }
            set {
                this["T01800_LETTER_KA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kh")]
        public string T01900_LETTER_KHA {
            get {
                return ((string)(this["T01900_LETTER_KHA"]));
            }
            set {
                this["T01900_LETTER_KHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("g")]
        public string T02000_LETTER_GA {
            get {
                return ((string)(this["T02000_LETTER_GA"]));
            }
            set {
                this["T02000_LETTER_GA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gh")]
        public string T02100_LETTER_GHA {
            get {
                return ((string)(this["T02100_LETTER_GHA"]));
            }
            set {
                this["T02100_LETTER_GHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~N")]
        public string T02200_LETTER_NGA {
            get {
                return ((string)(this["T02200_LETTER_NGA"]));
            }
            set {
                this["T02200_LETTER_NGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ch")]
        public string T02300_LETTER_CA {
            get {
                return ((string)(this["T02300_LETTER_CA"]));
            }
            set {
                this["T02300_LETTER_CA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ch")]
        public string T02400_LETTER_CHA {
            get {
                return ((string)(this["T02400_LETTER_CHA"]));
            }
            set {
                this["T02400_LETTER_CHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("j")]
        public string T02500_LETTER_JA {
            get {
                return ((string)(this["T02500_LETTER_JA"]));
            }
            set {
                this["T02500_LETTER_JA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jh")]
        public string T02600_LETTER_JHA {
            get {
                return ((string)(this["T02600_LETTER_JHA"]));
            }
            set {
                this["T02600_LETTER_JHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~n,GY")]
        public string T02700_LETTER_NYA {
            get {
                return ((string)(this["T02700_LETTER_NYA"]));
            }
            set {
                this["T02700_LETTER_NYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string T02800_LETTER_TTA {
            get {
                return ((string)(this["T02800_LETTER_TTA"]));
            }
            set {
                this["T02800_LETTER_TTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Th")]
        public string T02900_LETTER_TTHA {
            get {
                return ((string)(this["T02900_LETTER_TTHA"]));
            }
            set {
                this["T02900_LETTER_TTHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string T03000_LETTER_DDA {
            get {
                return ((string)(this["T03000_LETTER_DDA"]));
            }
            set {
                this["T03000_LETTER_DDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dh")]
        public string T03100_LETTER_DDHA {
            get {
                return ((string)(this["T03100_LETTER_DDHA"]));
            }
            set {
                this["T03100_LETTER_DDHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string T03200_LETTER_NNA {
            get {
                return ((string)(this["T03200_LETTER_NNA"]));
            }
            set {
                this["T03200_LETTER_NNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t")]
        public string T03300_LETTER_TA {
            get {
                return ((string)(this["T03300_LETTER_TA"]));
            }
            set {
                this["T03300_LETTER_TA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("th")]
        public string T03400_LETTER_THA {
            get {
                return ((string)(this["T03400_LETTER_THA"]));
            }
            set {
                this["T03400_LETTER_THA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d")]
        public string T03500_LETTER_DA {
            get {
                return ((string)(this["T03500_LETTER_DA"]));
            }
            set {
                this["T03500_LETTER_DA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dh")]
        public string T03600_LETTER_DHA {
            get {
                return ((string)(this["T03600_LETTER_DHA"]));
            }
            set {
                this["T03600_LETTER_DHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public string T03700_LETTER_NA {
            get {
                return ((string)(this["T03700_LETTER_NA"]));
            }
            set {
                this["T03700_LETTER_NA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p")]
        public string T03800_LETTER_PA {
            get {
                return ((string)(this["T03800_LETTER_PA"]));
            }
            set {
                this["T03800_LETTER_PA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ph")]
        public string T03900_LETTER_PHA {
            get {
                return ((string)(this["T03900_LETTER_PHA"]));
            }
            set {
                this["T03900_LETTER_PHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b")]
        public string T04000_LETTER_BA {
            get {
                return ((string)(this["T04000_LETTER_BA"]));
            }
            set {
                this["T04000_LETTER_BA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bh")]
        public string T04100_LETTER_BHA {
            get {
                return ((string)(this["T04100_LETTER_BHA"]));
            }
            set {
                this["T04100_LETTER_BHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string T04200_LETTER_MA {
            get {
                return ((string)(this["T04200_LETTER_MA"]));
            }
            set {
                this["T04200_LETTER_MA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y")]
        public string T04300_LETTER_YA {
            get {
                return ((string)(this["T04300_LETTER_YA"]));
            }
            set {
                this["T04300_LETTER_YA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("r")]
        public string T04400_LETTER_RA {
            get {
                return ((string)(this["T04400_LETTER_RA"]));
            }
            set {
                this["T04400_LETTER_RA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rx, #  bandi-raa or sakata-rEphamu in Telugu")]
        public string T04500_LETTER_RRA {
            get {
                return ((string)(this["T04500_LETTER_RRA"]));
            }
            set {
                this["T04500_LETTER_RRA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("l")]
        public string T04600_LETTER_LA {
            get {
                return ((string)(this["T04600_LETTER_LA"]));
            }
            set {
                this["T04600_LETTER_LA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L,ld ")]
        public string T04700_LETTER_LLA {
            get {
                return ((string)(this["T04700_LETTER_LLA"]));
            }
            set {
                this["T04700_LETTER_LLA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v,w")]
        public string T04800_LETTER_VA {
            get {
                return ((string)(this["T04800_LETTER_VA"]));
            }
            set {
                this["T04800_LETTER_VA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sh")]
        public string T04900_LETTER_SHA {
            get {
                return ((string)(this["T04900_LETTER_SHA"]));
            }
            set {
                this["T04900_LETTER_SHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sh")]
        public string T05000_LETTER_SSA {
            get {
                return ((string)(this["T05000_LETTER_SSA"]));
            }
            set {
                this["T05000_LETTER_SSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s")]
        public string T05100_LETTER_SA {
            get {
                return ((string)(this["T05100_LETTER_SA"]));
            }
            set {
                this["T05100_LETTER_SA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h")]
        public string T05200_LETTER_HA {
            get {
                return ((string)(this["T05200_LETTER_HA"]));
            }
            set {
                this["T05200_LETTER_HA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x,Ksh")]
        public string T05300_CONJUNCT_KSHA {
            get {
                return ((string)(this["T05300_CONJUNCT_KSHA"]));
            }
            set {
                this["T05300_CONJUNCT_KSHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xaa,XA")]
        public string T05400_VOWEL_SIGN_AA {
            get {
                return ((string)(this["T05400_VOWEL_SIGN_AA"]));
            }
            set {
                this["T05400_VOWEL_SIGN_AA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xi")]
        public string T05500_VOWEL_SIGN_I {
            get {
                return ((string)(this["T05500_VOWEL_SIGN_I"]));
            }
            set {
                this["T05500_VOWEL_SIGN_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xii,XI")]
        public string T05600_VOWEL_SIGN_II {
            get {
                return ((string)(this["T05600_VOWEL_SIGN_II"]));
            }
            set {
                this["T05600_VOWEL_SIGN_II"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xu")]
        public string T05700_VOWEL_SIGN_U {
            get {
                return ((string)(this["T05700_VOWEL_SIGN_U"]));
            }
            set {
                this["T05700_VOWEL_SIGN_U"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xuu,XU")]
        public string T05800_VOWEL_SIGN_UU {
            get {
                return ((string)(this["T05800_VOWEL_SIGN_UU"]));
            }
            set {
                this["T05800_VOWEL_SIGN_UU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XR^i")]
        public string T05900_VOWEL_SIGN_VOCALIC_R {
            get {
                return ((string)(this["T05900_VOWEL_SIGN_VOCALIC_R"]));
            }
            set {
                this["T05900_VOWEL_SIGN_VOCALIC_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XR^I")]
        public string T06000_VOWEL_SIGN_VOCALIC_RR {
            get {
                return ((string)(this["T06000_VOWEL_SIGN_VOCALIC_RR"]));
            }
            set {
                this["T06000_VOWEL_SIGN_VOCALIC_RR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xe")]
        public string T06100_VOWEL_SIGN_E {
            get {
                return ((string)(this["T06100_VOWEL_SIGN_E"]));
            }
            set {
                this["T06100_VOWEL_SIGN_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xee,XE")]
        public string T06200_VOWEL_SIGN_EE {
            get {
                return ((string)(this["T06200_VOWEL_SIGN_EE"]));
            }
            set {
                this["T06200_VOWEL_SIGN_EE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xai")]
        public string T06300_VOWEL_SIGN_AI {
            get {
                return ((string)(this["T06300_VOWEL_SIGN_AI"]));
            }
            set {
                this["T06300_VOWEL_SIGN_AI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xo")]
        public string T06400_VOWEL_SIGN_O {
            get {
                return ((string)(this["T06400_VOWEL_SIGN_O"]));
            }
            set {
                this["T06400_VOWEL_SIGN_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xoo,XO")]
        public string T06500_VOWEL_SIGN_OO {
            get {
                return ((string)(this["T06500_VOWEL_SIGN_OO"]));
            }
            set {
                this["T06500_VOWEL_SIGN_OO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xau")]
        public string T06600_VOWEL_SIGN_AU {
            get {
                return ((string)(this["T06600_VOWEL_SIGN_AU"]));
            }
            set {
                this["T06600_VOWEL_SIGN_AU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".h")]
        public string T06700_SIGN_VIRAMA {
            get {
                return ((string)(this["T06700_SIGN_VIRAMA"]));
            }
            set {
                this["T06700_SIGN_VIRAMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XAA")]
        public string T06800_LENGTH_MARK {
            get {
                return ((string)(this["T06800_LENGTH_MARK"]));
            }
            set {
                this["T06800_LENGTH_MARK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XAI")]
        public string T06900_AI_LENGTH_MARK {
            get {
                return ((string)(this["T06900_AI_LENGTH_MARK"]));
            }
            set {
                this["T06900_AI_LENGTH_MARK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R^I,RRI")]
        public string T07000_LETTER_VOCALIC_RR {
            get {
                return ((string)(this["T07000_LETTER_VOCALIC_RR"]));
            }
            set {
                this["T07000_LETTER_VOCALIC_RR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L^I,LLI")]
        public string T07100_LETTER_VOCALIC_LL {
            get {
                return ((string)(this["T07100_LETTER_VOCALIC_LL"]));
            }
            set {
                this["T07100_LETTER_VOCALIC_LL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string T07200_DIGIT_ZERO {
            get {
                return ((string)(this["T07200_DIGIT_ZERO"]));
            }
            set {
                this["T07200_DIGIT_ZERO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string T07300_DIGIT_ONE {
            get {
                return ((string)(this["T07300_DIGIT_ONE"]));
            }
            set {
                this["T07300_DIGIT_ONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string T07400_DIGIT_TWO {
            get {
                return ((string)(this["T07400_DIGIT_TWO"]));
            }
            set {
                this["T07400_DIGIT_TWO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string T07500_DIGIT_THREE {
            get {
                return ((string)(this["T07500_DIGIT_THREE"]));
            }
            set {
                this["T07500_DIGIT_THREE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string T07600_DIGIT_FOUR {
            get {
                return ((string)(this["T07600_DIGIT_FOUR"]));
            }
            set {
                this["T07600_DIGIT_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string T07700_DIGIT_FIVE {
            get {
                return ((string)(this["T07700_DIGIT_FIVE"]));
            }
            set {
                this["T07700_DIGIT_FIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string T07800_DIGIT_SIX {
            get {
                return ((string)(this["T07800_DIGIT_SIX"]));
            }
            set {
                this["T07800_DIGIT_SIX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string T07900_DIGIT_SEVEN {
            get {
                return ((string)(this["T07900_DIGIT_SEVEN"]));
            }
            set {
                this["T07900_DIGIT_SEVEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string T08000_DIGIT_EIGHT {
            get {
                return ((string)(this["T08000_DIGIT_EIGHT"]));
            }
            set {
                this["T08000_DIGIT_EIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string T08100_DIGIT_NINE {
            get {
                return ((string)(this["T08100_DIGIT_NINE"]));
            }
            set {
                this["T08100_DIGIT_NINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".a")]
        public string T08200_SIGN_AVAGRAHA {
            get {
                return ((string)(this["T08200_SIGN_AVAGRAHA"]));
            }
            set {
                this["T08200_SIGN_AVAGRAHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OM,AUM")]
        public string T08300_SIGN_OM {
            get {
                return ((string)(this["T08300_SIGN_OM"]));
            }
            set {
                this["T08300_SIGN_OM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\`,\\_")]
        public string T08400_SIGN_ANUDATTA {
            get {
                return ((string)(this["T08400_SIGN_ANUDATTA"]));
            }
            set {
                this["T08400_SIGN_ANUDATTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\'")]
        public string T08500_SIGN_SWARITA {
            get {
                return ((string)(this["T08500_SIGN_SWARITA"]));
            }
            set {
                this["T08500_SIGN_SWARITA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\"")]
        public string T08600_SIGN_DEERGHA_SWARITA {
            get {
                return ((string)(this["T08600_SIGN_DEERGHA_SWARITA"]));
            }
            set {
                this["T08600_SIGN_DEERGHA_SWARITA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\m+")]
        public string T08700_CONJUNCT_GUM {
            get {
                return ((string)(this["T08700_CONJUNCT_GUM"]));
            }
            set {
                this["T08700_CONJUNCT_GUM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tsa")]
        public string T08800_TELUGU_LETTER_TSA {
            get {
                return ((string)(this["T08800_TELUGU_LETTER_TSA"]));
            }
            set {
                this["T08800_TELUGU_LETTER_TSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".L")]
        public string T08900_TELUGU_VOWEL_SIGN_VOCALIC_L {
            get {
                return ((string)(this["T08900_TELUGU_VOWEL_SIGN_VOCALIC_L"]));
            }
            set {
                this["T08900_TELUGU_VOWEL_SIGN_VOCALIC_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".LL")]
        public string T09000_TELUGU_VOWEL_SIGN_VOCALIC_LL {
            get {
                return ((string)(this["T09000_TELUGU_VOWEL_SIGN_VOCALIC_LL"]));
            }
            set {
                this["T09000_TELUGU_VOWEL_SIGN_VOCALIC_LL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".c")]
        public string T09100_TELUGU_SIGN_ARDHAVISARGA {
            get {
                return ((string)(this["T09100_TELUGU_SIGN_ARDHAVISARGA"]));
            }
            set {
                this["T09100_TELUGU_SIGN_ARDHAVISARGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw1")]
        public string T09200_TELUGU_FRACTION_AND_WEIGHT_SIGN1 {
            get {
                return ((string)(this["T09200_TELUGU_FRACTION_AND_WEIGHT_SIGN1"]));
            }
            set {
                this["T09200_TELUGU_FRACTION_AND_WEIGHT_SIGN1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw2")]
        public string T09300_TELUGU_FRACTION_AND_WEIGHT_SIGN2 {
            get {
                return ((string)(this["T09300_TELUGU_FRACTION_AND_WEIGHT_SIGN2"]));
            }
            set {
                this["T09300_TELUGU_FRACTION_AND_WEIGHT_SIGN2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw3")]
        public string T09400_TELUGU_FRACTION_AND_WEIGHT_SIGN3 {
            get {
                return ((string)(this["T09400_TELUGU_FRACTION_AND_WEIGHT_SIGN3"]));
            }
            set {
                this["T09400_TELUGU_FRACTION_AND_WEIGHT_SIGN3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw4")]
        public string T09500_TELUGU_FRACTION_AND_WEIGHT_SIGN4 {
            get {
                return ((string)(this["T09500_TELUGU_FRACTION_AND_WEIGHT_SIGN4"]));
            }
            set {
                this["T09500_TELUGU_FRACTION_AND_WEIGHT_SIGN4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw5")]
        public string T09600_TELUGU_FRACTION_AND_WEIGHT_SIGN5 {
            get {
                return ((string)(this["T09600_TELUGU_FRACTION_AND_WEIGHT_SIGN5"]));
            }
            set {
                this["T09600_TELUGU_FRACTION_AND_WEIGHT_SIGN5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw6")]
        public string T09700_TELUGU_FRACTION_AND_WEIGHT_SIGN6 {
            get {
                return ((string)(this["T09700_TELUGU_FRACTION_AND_WEIGHT_SIGN6"]));
            }
            set {
                this["T09700_TELUGU_FRACTION_AND_WEIGHT_SIGN6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw7")]
        public string T09800_TELUGU_FRACTION_AND_WEIGHT_SIGN7 {
            get {
                return ((string)(this["T09800_TELUGU_FRACTION_AND_WEIGHT_SIGN7"]));
            }
            set {
                this["T09800_TELUGU_FRACTION_AND_WEIGHT_SIGN7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fw8")]
        public string T09900_TELUGU_FRACTION_AND_WEIGHT_SIGN8 {
            get {
                return ((string)(this["T09900_TELUGU_FRACTION_AND_WEIGHT_SIGN8"]));
            }
            set {
                this["T09900_TELUGU_FRACTION_AND_WEIGHT_SIGN8"] = value;
            }
        }
    }
}
