//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumPad {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Fonts : global::System.Configuration.ApplicationSettingsBase {
        
        private static Fonts defaultInstance = ((Fonts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Fonts())));
        
        public static Fonts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vrinda, 14.25pt")]
        public global::System.Drawing.Font BENGALI {
            get {
                return ((global::System.Drawing.Font)(this["BENGALI"]));
            }
            set {
                this["BENGALI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mangal, 14.25pt")]
        public global::System.Drawing.Font DEVANAGARI {
            get {
                return ((global::System.Drawing.Font)(this["DEVANAGARI"]));
            }
            set {
                this["DEVANAGARI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shruti, 14.25pt")]
        public global::System.Drawing.Font GUJARATI {
            get {
                return ((global::System.Drawing.Font)(this["GUJARATI"]));
            }
            set {
                this["GUJARATI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Raavi, 14.25pt")]
        public global::System.Drawing.Font GURMUKHI {
            get {
                return ((global::System.Drawing.Font)(this["GURMUKHI"]));
            }
            set {
                this["GURMUKHI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tunga, 14.25pt")]
        public global::System.Drawing.Font KANNADA {
            get {
                return ((global::System.Drawing.Font)(this["KANNADA"]));
            }
            set {
                this["KANNADA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kartika, 14.25pt")]
        public global::System.Drawing.Font MALAYALAM {
            get {
                return ((global::System.Drawing.Font)(this["MALAYALAM"]));
            }
            set {
                this["MALAYALAM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mangal, 14.25pt")]
        public global::System.Drawing.Font MARATHI {
            get {
                return ((global::System.Drawing.Font)(this["MARATHI"]));
            }
            set {
                this["MARATHI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kalinga, 14.25pt")]
        public global::System.Drawing.Font ORIYA {
            get {
                return ((global::System.Drawing.Font)(this["ORIYA"]));
            }
            set {
                this["ORIYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Latha, 14.25pt")]
        public global::System.Drawing.Font TAMIL {
            get {
                return ((global::System.Drawing.Font)(this["TAMIL"]));
            }
            set {
                this["TAMIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gautami, 14.25pt")]
        public global::System.Drawing.Font TELUGU {
            get {
                return ((global::System.Drawing.Font)(this["TELUGU"]));
            }
            set {
                this["TELUGU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial, 12pt")]
        public global::System.Drawing.Font LATIN {
            get {
                return ((global::System.Drawing.Font)(this["LATIN"]));
            }
            set {
                this["LATIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial Unicode MS, 12pt")]
        public global::System.Drawing.Font LATINEX {
            get {
                return ((global::System.Drawing.Font)(this["LATINEX"]));
            }
            set {
                this["LATINEX"] = value;
            }
        }
    }
}
