//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GumLib {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Map : global::System.Configuration.ApplicationSettingsBase {
        
        private static Map defaultInstance = ((Map)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Map())));
        
        public static Map Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".n")]
        public string A0010_SIGN_CANDRABINDU {
            get {
                return ((string)(this["A0010_SIGN_CANDRABINDU"]));
            }
            set {
                this["A0010_SIGN_CANDRABINDU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string A0020_SIGN_ANUSVARA {
            get {
                return ((string)(this["A0020_SIGN_ANUSVARA"]));
            }
            set {
                this["A0020_SIGN_ANUSVARA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string A0030_SIGN_VISARGA {
            get {
                return ((string)(this["A0030_SIGN_VISARGA"]));
            }
            set {
                this["A0030_SIGN_VISARGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^a")]
        public string A0040_LETTER_SHORT_A {
            get {
                return ((string)(this["A0040_LETTER_SHORT_A"]));
            }
            set {
                this["A0040_LETTER_SHORT_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a")]
        public string A0050_LETTER_A {
            get {
                return ((string)(this["A0050_LETTER_A"]));
            }
            set {
                this["A0050_LETTER_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aa,A")]
        public string A0060_LETTER_AA {
            get {
                return ((string)(this["A0060_LETTER_AA"]));
            }
            set {
                this["A0060_LETTER_AA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i")]
        public string A0070_LETTER_I {
            get {
                return ((string)(this["A0070_LETTER_I"]));
            }
            set {
                this["A0070_LETTER_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ii,I")]
        public string A0080_LETTER_II {
            get {
                return ((string)(this["A0080_LETTER_II"]));
            }
            set {
                this["A0080_LETTER_II"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("u")]
        public string A0090_LETTER_U {
            get {
                return ((string)(this["A0090_LETTER_U"]));
            }
            set {
                this["A0090_LETTER_U"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uu,U")]
        public string A0100_LETTER_UU {
            get {
                return ((string)(this["A0100_LETTER_UU"]));
            }
            set {
                this["A0100_LETTER_UU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RRi,R^i")]
        public string A0110_LETTER_VOCALIC_R {
            get {
                return ((string)(this["A0110_LETTER_VOCALIC_R"]));
            }
            set {
                this["A0110_LETTER_VOCALIC_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RRI,R^I")]
        public string A0120_LETTER_VOCALIC_RR {
            get {
                return ((string)(this["A0120_LETTER_VOCALIC_RR"]));
            }
            set {
                this["A0120_LETTER_VOCALIC_RR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LLi,L^i")]
        public string A0130_LETTER_VOCALIC_L {
            get {
                return ((string)(this["A0130_LETTER_VOCALIC_L"]));
            }
            set {
                this["A0130_LETTER_VOCALIC_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LLI,L^I")]
        public string A0140_LETTER_VOCALIC_LL {
            get {
                return ((string)(this["A0140_LETTER_VOCALIC_LL"]));
            }
            set {
                this["A0140_LETTER_VOCALIC_LL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^e")]
        public string A0150_LETTER_CANDRA_E {
            get {
                return ((string)(this["A0150_LETTER_CANDRA_E"]));
            }
            set {
                this["A0150_LETTER_CANDRA_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e")]
        public string A0160_LETTER_E {
            get {
                return ((string)(this["A0160_LETTER_E"]));
            }
            set {
                this["A0160_LETTER_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ee,E")]
        public string A0170_LETTER_EE {
            get {
                return ((string)(this["A0170_LETTER_EE"]));
            }
            set {
                this["A0170_LETTER_EE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ai")]
        public string A0180_LETTER_AI {
            get {
                return ((string)(this["A0180_LETTER_AI"]));
            }
            set {
                this["A0180_LETTER_AI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^o")]
        public string A0190_LETTER_CANDRA_O {
            get {
                return ((string)(this["A0190_LETTER_CANDRA_O"]));
            }
            set {
                this["A0190_LETTER_CANDRA_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("o")]
        public string A0200_LETTER_O {
            get {
                return ((string)(this["A0200_LETTER_O"]));
            }
            set {
                this["A0200_LETTER_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oo,O")]
        public string A0210_LETTER_OO {
            get {
                return ((string)(this["A0210_LETTER_OO"]));
            }
            set {
                this["A0210_LETTER_OO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("au")]
        public string A0220_LETTER_AU {
            get {
                return ((string)(this["A0220_LETTER_AU"]));
            }
            set {
                this["A0220_LETTER_AU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("k")]
        public string A0230_LETTER_KA {
            get {
                return ((string)(this["A0230_LETTER_KA"]));
            }
            set {
                this["A0230_LETTER_KA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kk")]
        public string A0240_CONJUNCT_KKA {
            get {
                return ((string)(this["A0240_CONJUNCT_KKA"]));
            }
            set {
                this["A0240_CONJUNCT_KKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kh")]
        public string A0250_LETTER_KHA {
            get {
                return ((string)(this["A0250_LETTER_KHA"]));
            }
            set {
                this["A0250_LETTER_KHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("g")]
        public string A0260_LETTER_GA {
            get {
                return ((string)(this["A0260_LETTER_GA"]));
            }
            set {
                this["A0260_LETTER_GA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ga.n")]
        public string A0270_CONJUNCT_GUM {
            get {
                return ((string)(this["A0270_CONJUNCT_GUM"]));
            }
            set {
                this["A0270_CONJUNCT_GUM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gh")]
        public string A0280_LETTER_GHA {
            get {
                return ((string)(this["A0280_LETTER_GHA"]));
            }
            set {
                this["A0280_LETTER_GHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~N,N^")]
        public string A0290_LETTER_NGA {
            get {
                return ((string)(this["A0290_LETTER_NGA"]));
            }
            set {
                this["A0290_LETTER_NGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ch")]
        public string A0300_LETTER_CA {
            get {
                return ((string)(this["A0300_LETTER_CA"]));
            }
            set {
                this["A0300_LETTER_CA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chh")]
        public string A0310_LETTER_CHA {
            get {
                return ((string)(this["A0310_LETTER_CHA"]));
            }
            set {
                this["A0310_LETTER_CHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("j")]
        public string A0320_LETTER_JA {
            get {
                return ((string)(this["A0320_LETTER_JA"]));
            }
            set {
                this["A0320_LETTER_JA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jh")]
        public string A0330_LETTER_JHA {
            get {
                return ((string)(this["A0330_LETTER_JHA"]));
            }
            set {
                this["A0330_LETTER_JHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~n,JN")]
        public string A0340_LETTER_NYA {
            get {
                return ((string)(this["A0340_LETTER_NYA"]));
            }
            set {
                this["A0340_LETTER_NYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string A0350_LETTER_TTA {
            get {
                return ((string)(this["A0350_LETTER_TTA"]));
            }
            set {
                this["A0350_LETTER_TTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Th")]
        public string A0360_LETTER_TTHA {
            get {
                return ((string)(this["A0360_LETTER_TTHA"]));
            }
            set {
                this["A0360_LETTER_TTHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string A0370_LETTER_DDA {
            get {
                return ((string)(this["A0370_LETTER_DDA"]));
            }
            set {
                this["A0370_LETTER_DDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dh")]
        public string A0380_LETTER_DDHA {
            get {
                return ((string)(this["A0380_LETTER_DDHA"]));
            }
            set {
                this["A0380_LETTER_DDHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N")]
        public string A0390_LETTER_NNA {
            get {
                return ((string)(this["A0390_LETTER_NNA"]));
            }
            set {
                this["A0390_LETTER_NNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t")]
        public string A0400_LETTER_TA {
            get {
                return ((string)(this["A0400_LETTER_TA"]));
            }
            set {
                this["A0400_LETTER_TA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("th")]
        public string A0410_LETTER_THA {
            get {
                return ((string)(this["A0410_LETTER_THA"]));
            }
            set {
                this["A0410_LETTER_THA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d")]
        public string A0420_LETTER_DA {
            get {
                return ((string)(this["A0420_LETTER_DA"]));
            }
            set {
                this["A0420_LETTER_DA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dh")]
        public string A0430_LETTER_DHA {
            get {
                return ((string)(this["A0430_LETTER_DHA"]));
            }
            set {
                this["A0430_LETTER_DHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("n")]
        public string A0440_LETTER_NA {
            get {
                return ((string)(this["A0440_LETTER_NA"]));
            }
            set {
                this["A0440_LETTER_NA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N.")]
        public string A0450_LETTER_NNNA {
            get {
                return ((string)(this["A0450_LETTER_NNNA"]));
            }
            set {
                this["A0450_LETTER_NNNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("p")]
        public string A0460_LETTER_PA {
            get {
                return ((string)(this["A0460_LETTER_PA"]));
            }
            set {
                this["A0460_LETTER_PA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ph")]
        public string A0470_LETTER_PHA {
            get {
                return ((string)(this["A0470_LETTER_PHA"]));
            }
            set {
                this["A0470_LETTER_PHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b")]
        public string A0480_LETTER_BA {
            get {
                return ((string)(this["A0480_LETTER_BA"]));
            }
            set {
                this["A0480_LETTER_BA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bh")]
        public string A0490_LETTER_BHA {
            get {
                return ((string)(this["A0490_LETTER_BHA"]));
            }
            set {
                this["A0490_LETTER_BHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string A0500_LETTER_MA {
            get {
                return ((string)(this["A0500_LETTER_MA"]));
            }
            set {
                this["A0500_LETTER_MA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y")]
        public string A0510_LETTER_YA {
            get {
                return ((string)(this["A0510_LETTER_YA"]));
            }
            set {
                this["A0510_LETTER_YA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("r")]
        public string A0520_LETTER_RA {
            get {
                return ((string)(this["A0520_LETTER_RA"]));
            }
            set {
                this["A0520_LETTER_RA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string A0530_LETTER_RRA {
            get {
                return ((string)(this["A0530_LETTER_RRA"]));
            }
            set {
                this["A0530_LETTER_RRA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("l")]
        public string A0540_LETTER_LA {
            get {
                return ((string)(this["A0540_LETTER_LA"]));
            }
            set {
                this["A0540_LETTER_LA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L")]
        public string A0550_LETTER_LLA {
            get {
                return ((string)(this["A0550_LETTER_LLA"]));
            }
            set {
                this["A0550_LETTER_LLA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".L")]
        public string A0560_LETTER_LLLA {
            get {
                return ((string)(this["A0560_LETTER_LLLA"]));
            }
            set {
                this["A0560_LETTER_LLLA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v,w")]
        public string A0570_LETTER_VA {
            get {
                return ((string)(this["A0570_LETTER_VA"]));
            }
            set {
                this["A0570_LETTER_VA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sh")]
        public string A0580_LETTER_SHA {
            get {
                return ((string)(this["A0580_LETTER_SHA"]));
            }
            set {
                this["A0580_LETTER_SHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sh,shh")]
        public string A0590_LETTER_SSA {
            get {
                return ((string)(this["A0590_LETTER_SSA"]));
            }
            set {
                this["A0590_LETTER_SSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("s")]
        public string A0600_LETTER_SA {
            get {
                return ((string)(this["A0600_LETTER_SA"]));
            }
            set {
                this["A0600_LETTER_SA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h")]
        public string A0610_LETTER_HA {
            get {
                return ((string)(this["A0610_LETTER_HA"]));
            }
            set {
                this["A0610_LETTER_HA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x,kSh")]
        public string A0620_CONJUNCT_KSHA {
            get {
                return ((string)(this["A0620_CONJUNCT_KSHA"]));
            }
            set {
                this["A0620_CONJUNCT_KSHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^n")]
        public string A0630_SIGN_NUKTA {
            get {
                return ((string)(this["A0630_SIGN_NUKTA"]));
            }
            set {
                this["A0630_SIGN_NUKTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".a")]
        public string A0640_SIGN_AVAGRAHA {
            get {
                return ((string)(this["A0640_SIGN_AVAGRAHA"]));
            }
            set {
                this["A0640_SIGN_AVAGRAHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xaa,XA")]
        public string A0650_VOWEL_SIGN_AA {
            get {
                return ((string)(this["A0650_VOWEL_SIGN_AA"]));
            }
            set {
                this["A0650_VOWEL_SIGN_AA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xi")]
        public string A0660_VOWEL_SIGN_I {
            get {
                return ((string)(this["A0660_VOWEL_SIGN_I"]));
            }
            set {
                this["A0660_VOWEL_SIGN_I"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xii,XI")]
        public string A0670_VOWEL_SIGN_II {
            get {
                return ((string)(this["A0670_VOWEL_SIGN_II"]));
            }
            set {
                this["A0670_VOWEL_SIGN_II"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xu")]
        public string A0680_VOWEL_SIGN_U {
            get {
                return ((string)(this["A0680_VOWEL_SIGN_U"]));
            }
            set {
                this["A0680_VOWEL_SIGN_U"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xuu,XU")]
        public string A0690_VOWEL_SIGN_UU {
            get {
                return ((string)(this["A0690_VOWEL_SIGN_UU"]));
            }
            set {
                this["A0690_VOWEL_SIGN_UU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XR^i")]
        public string A0700_VOWEL_SIGN_VOCALIC_R {
            get {
                return ((string)(this["A0700_VOWEL_SIGN_VOCALIC_R"]));
            }
            set {
                this["A0700_VOWEL_SIGN_VOCALIC_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XR^I")]
        public string A0710_VOWEL_SIGN_VOCALIC_RR {
            get {
                return ((string)(this["A0710_VOWEL_SIGN_VOCALIC_RR"]));
            }
            set {
                this["A0710_VOWEL_SIGN_VOCALIC_RR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XL^i")]
        public string A0720_SIGN_VOCALIC_L {
            get {
                return ((string)(this["A0720_SIGN_VOCALIC_L"]));
            }
            set {
                this["A0720_SIGN_VOCALIC_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XL^I")]
        public string A0730_SIGN_VOCALIC_LL {
            get {
                return ((string)(this["A0730_SIGN_VOCALIC_LL"]));
            }
            set {
                this["A0730_SIGN_VOCALIC_LL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X^e")]
        public string A0740_VOWEL_SIGN_CANDRA_E {
            get {
                return ((string)(this["A0740_VOWEL_SIGN_CANDRA_E"]));
            }
            set {
                this["A0740_VOWEL_SIGN_CANDRA_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xe")]
        public string A0750_VOWEL_SIGN_E {
            get {
                return ((string)(this["A0750_VOWEL_SIGN_E"]));
            }
            set {
                this["A0750_VOWEL_SIGN_E"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xee,XE")]
        public string A0760_VOWEL_SIGN_EE {
            get {
                return ((string)(this["A0760_VOWEL_SIGN_EE"]));
            }
            set {
                this["A0760_VOWEL_SIGN_EE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xai")]
        public string A0770_VOWEL_SIGN_AI {
            get {
                return ((string)(this["A0770_VOWEL_SIGN_AI"]));
            }
            set {
                this["A0770_VOWEL_SIGN_AI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X^o")]
        public string A0780_VOWEL_SIGN_CANDRA_O {
            get {
                return ((string)(this["A0780_VOWEL_SIGN_CANDRA_O"]));
            }
            set {
                this["A0780_VOWEL_SIGN_CANDRA_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xo")]
        public string A0790_VOWEL_SIGN_O {
            get {
                return ((string)(this["A0790_VOWEL_SIGN_O"]));
            }
            set {
                this["A0790_VOWEL_SIGN_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xoo,XO")]
        public string A0800_VOWEL_SIGN_OO {
            get {
                return ((string)(this["A0800_VOWEL_SIGN_OO"]));
            }
            set {
                this["A0800_VOWEL_SIGN_OO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xau")]
        public string A0810_VOWEL_SIGN_AU {
            get {
                return ((string)(this["A0810_VOWEL_SIGN_AU"]));
            }
            set {
                this["A0810_VOWEL_SIGN_AU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".h")]
        public string A0820_SIGN_VIRAMA {
            get {
                return ((string)(this["A0820_SIGN_VIRAMA"]));
            }
            set {
                this["A0820_SIGN_VIRAMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("om,OM,AUM")]
        public string A0830_SIGN_OM {
            get {
                return ((string)(this["A0830_SIGN_OM"]));
            }
            set {
                this["A0830_SIGN_OM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\'")]
        public string A0840_SIGN_UDATTA {
            get {
                return ((string)(this["A0840_SIGN_UDATTA"]));
            }
            set {
                this["A0840_SIGN_UDATTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\_")]
        public string A0850_SIGN_ANUDATTA {
            get {
                return ((string)(this["A0850_SIGN_ANUDATTA"]));
            }
            set {
                this["A0850_SIGN_ANUDATTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".r")]
        public string A0860_SIGN_GRAVE_ACCENT {
            get {
                return ((string)(this["A0860_SIGN_GRAVE_ACCENT"]));
            }
            set {
                this["A0860_SIGN_GRAVE_ACCENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".e")]
        public string A0870_SIGN_ACUTE_ACCENT {
            get {
                return ((string)(this["A0870_SIGN_ACUTE_ACCENT"]));
            }
            set {
                this["A0870_SIGN_ACUTE_ACCENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XAA")]
        public string A0880_LENGTH_MARK {
            get {
                return ((string)(this["A0880_LENGTH_MARK"]));
            }
            set {
                this["A0880_LENGTH_MARK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XAI")]
        public string A0890_AI_LENGTH_MARK {
            get {
                return ((string)(this["A0890_AI_LENGTH_MARK"]));
            }
            set {
                this["A0890_AI_LENGTH_MARK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XAU")]
        public string A0900_AU_LENGTH_MARK {
            get {
                return ((string)(this["A0900_AU_LENGTH_MARK"]));
            }
            set {
                this["A0900_AU_LENGTH_MARK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\`")]
        public string A0910_SIGN_SWARITA {
            get {
                return ((string)(this["A0910_SIGN_SWARITA"]));
            }
            set {
                this["A0910_SIGN_SWARITA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\"")]
        public string A0920_SIGN_DEERGHA_SWARITA {
            get {
                return ((string)(this["A0920_SIGN_DEERGHA_SWARITA"]));
            }
            set {
                this["A0920_SIGN_DEERGHA_SWARITA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|")]
        public string A0930_SIGN_DANDA {
            get {
                return ((string)(this["A0930_SIGN_DANDA"]));
            }
            set {
                this["A0930_SIGN_DANDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("||")]
        public string A0940_SIGN_DOUBLE_DANDA {
            get {
                return ((string)(this["A0940_SIGN_DOUBLE_DANDA"]));
            }
            set {
                this["A0940_SIGN_DOUBLE_DANDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string A0950_DIGIT_ZERO {
            get {
                return ((string)(this["A0950_DIGIT_ZERO"]));
            }
            set {
                this["A0950_DIGIT_ZERO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string A0960_DIGIT_ONE {
            get {
                return ((string)(this["A0960_DIGIT_ONE"]));
            }
            set {
                this["A0960_DIGIT_ONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string A0970_DIGIT_TWO {
            get {
                return ((string)(this["A0970_DIGIT_TWO"]));
            }
            set {
                this["A0970_DIGIT_TWO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string A0980_DIGIT_THREE {
            get {
                return ((string)(this["A0980_DIGIT_THREE"]));
            }
            set {
                this["A0980_DIGIT_THREE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string A0990_DIGIT_FOUR {
            get {
                return ((string)(this["A0990_DIGIT_FOUR"]));
            }
            set {
                this["A0990_DIGIT_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string A1000_DIGIT_FIVE {
            get {
                return ((string)(this["A1000_DIGIT_FIVE"]));
            }
            set {
                this["A1000_DIGIT_FIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public string A1010_DIGIT_SIX {
            get {
                return ((string)(this["A1010_DIGIT_SIX"]));
            }
            set {
                this["A1010_DIGIT_SIX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string A1020_DIGIT_SEVEN {
            get {
                return ((string)(this["A1020_DIGIT_SEVEN"]));
            }
            set {
                this["A1020_DIGIT_SEVEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string A1030_DIGIT_EIGHT {
            get {
                return ((string)(this["A1030_DIGIT_EIGHT"]));
            }
            set {
                this["A1030_DIGIT_EIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public string A1040_DIGIT_NINE {
            get {
                return ((string)(this["A1040_DIGIT_NINE"]));
            }
            set {
                this["A1040_DIGIT_NINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("om")]
        public string B0010_DEVANAGARI_SIGN_OM {
            get {
                return ((string)(this["B0010_DEVANAGARI_SIGN_OM"]));
            }
            set {
                this["B0010_DEVANAGARI_SIGN_OM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\_")]
        public string B0020_DEVANAGARI_SIGN_ANUDATTA {
            get {
                return ((string)(this["B0020_DEVANAGARI_SIGN_ANUDATTA"]));
            }
            set {
                this["B0020_DEVANAGARI_SIGN_ANUDATTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\'")]
        public string B0030_DEVANAGARI_SIGN_UDATTA {
            get {
                return ((string)(this["B0030_DEVANAGARI_SIGN_UDATTA"]));
            }
            set {
                this["B0030_DEVANAGARI_SIGN_UDATTA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("q")]
        public string B0040_DEVANAGARI_LETTER_QA {
            get {
                return ((string)(this["B0040_DEVANAGARI_LETTER_QA"]));
            }
            set {
                this["B0040_DEVANAGARI_LETTER_QA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K")]
        public string B0050_DEVANAGARI_LETTER_KHHA {
            get {
                return ((string)(this["B0050_DEVANAGARI_LETTER_KHHA"]));
            }
            set {
                this["B0050_DEVANAGARI_LETTER_KHHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gh")]
        public string B0060_DEVANAGARI_LETTER_GHHA {
            get {
                return ((string)(this["B0060_DEVANAGARI_LETTER_GHHA"]));
            }
            set {
                this["B0060_DEVANAGARI_LETTER_GHHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J,z")]
        public string B0070_DEVANAGARI_LETTER_ZA {
            get {
                return ((string)(this["B0070_DEVANAGARI_LETTER_ZA"]));
            }
            set {
                this["B0070_DEVANAGARI_LETTER_ZA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".Dh")]
        public string B0080_DEVANAGARI_LETTER_DDDHA {
            get {
                return ((string)(this["B0080_DEVANAGARI_LETTER_DDDHA"]));
            }
            set {
                this["B0080_DEVANAGARI_LETTER_DDDHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rh")]
        public string B0090_DEVANAGARI_LETTER_RHA {
            get {
                return ((string)(this["B0090_DEVANAGARI_LETTER_RHA"]));
            }
            set {
                this["B0090_DEVANAGARI_LETTER_RHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f")]
        public string B0100_DEVANAGARI_LETTER_FA {
            get {
                return ((string)(this["B0100_DEVANAGARI_LETTER_FA"]));
            }
            set {
                this["B0100_DEVANAGARI_LETTER_FA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string B0110_DEVANAGARI_LETTER_YYA {
            get {
                return ((string)(this["B0110_DEVANAGARI_LETTER_YYA"]));
            }
            set {
                this["B0110_DEVANAGARI_LETTER_YYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\.")]
        public string B0120_DEVANAGARI_ABBREVIATION_SIGN {
            get {
                return ((string)(this["B0120_DEVANAGARI_ABBREVIATION_SIGN"]));
            }
            set {
                this["B0120_DEVANAGARI_ABBREVIATION_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\^.")]
        public string B0130_DEVANAGARI_SIGN_HIGH_SPACING_DOT {
            get {
                return ((string)(this["B0130_DEVANAGARI_SIGN_HIGH_SPACING_DOT"]));
            }
            set {
                this["B0130_DEVANAGARI_SIGN_HIGH_SPACING_DOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^.a")]
        public string B0140_DEVANAGARI_LETTER_CANDRA_A {
            get {
                return ((string)(this["B0140_DEVANAGARI_LETTER_CANDRA_A"]));
            }
            set {
                this["B0140_DEVANAGARI_LETTER_CANDRA_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string B0150_DEVANAGARI_LETTER_GGA {
            get {
                return ((string)(this["B0150_DEVANAGARI_LETTER_GGA"]));
            }
            set {
                this["B0150_DEVANAGARI_LETTER_GGA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".J")]
        public string B0160_DEVANAGARI_LETTER_JJA {
            get {
                return ((string)(this["B0160_DEVANAGARI_LETTER_JJA"]));
            }
            set {
                this["B0160_DEVANAGARI_LETTER_JJA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".G")]
        public string B0170_DEVANAGARI_LETTER_GLOTTAL_STOP {
            get {
                return ((string)(this["B0170_DEVANAGARI_LETTER_GLOTTAL_STOP"]));
            }
            set {
                this["B0170_DEVANAGARI_LETTER_GLOTTAL_STOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".D")]
        public string B0180_DEVANAGARI_LETTER_DDDA {
            get {
                return ((string)(this["B0180_DEVANAGARI_LETTER_DDDA"]));
            }
            set {
                this["B0180_DEVANAGARI_LETTER_DDDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B")]
        public string B0190_DEVANAGARI_LETTER_BBA {
            get {
                return ((string)(this["B0190_DEVANAGARI_LETTER_BBA"]));
            }
            set {
                this["B0190_DEVANAGARI_LETTER_BBA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cs")]
        public string C0010_TELUGU_LETTER_TSA {
            get {
                return ((string)(this["C0010_TELUGU_LETTER_TSA"]));
            }
            set {
                this["C0010_TELUGU_LETTER_TSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dz")]
        public string C0020_TELUGU_LETTER_DZA {
            get {
                return ((string)(this["C0020_TELUGU_LETTER_DZA"]));
            }
            set {
                this["C0020_TELUGU_LETTER_DZA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".H")]
        public string C0030_TELUGU_FRACTION_DIGIT_ZERO_FOR_ODD_POWERS_OF_FOUR {
            get {
                return ((string)(this["C0030_TELUGU_FRACTION_DIGIT_ZERO_FOR_ODD_POWERS_OF_FOUR"]));
            }
            set {
                this["C0030_TELUGU_FRACTION_DIGIT_ZERO_FOR_ODD_POWERS_OF_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/4o")]
        public string C0040_TELUGU_FRACTION_DIGIT_ONE_FOR_ODD_POWERS_OF_FOUR {
            get {
                return ((string)(this["C0040_TELUGU_FRACTION_DIGIT_ONE_FOR_ODD_POWERS_OF_FOUR"]));
            }
            set {
                this["C0040_TELUGU_FRACTION_DIGIT_ONE_FOR_ODD_POWERS_OF_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2/4o")]
        public string C0050_TELUGU_FRACTION_DIGIT_TWO_FOR_ODD_POWERS_OF_FOUR {
            get {
                return ((string)(this["C0050_TELUGU_FRACTION_DIGIT_TWO_FOR_ODD_POWERS_OF_FOUR"]));
            }
            set {
                this["C0050_TELUGU_FRACTION_DIGIT_TWO_FOR_ODD_POWERS_OF_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3/4o")]
        public string C0060_TELUGU_FRACTION_DIGIT_THREE_FOR_ODD_POWERS_OF_FOUR {
            get {
                return ((string)(this["C0060_TELUGU_FRACTION_DIGIT_THREE_FOR_ODD_POWERS_OF_FOUR"]));
            }
            set {
                this["C0060_TELUGU_FRACTION_DIGIT_THREE_FOR_ODD_POWERS_OF_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/4e")]
        public string C0070_TELUGU_FRACTION_DIGIT_ONE_FOR_EVEN_POWERS_OF_FOUR {
            get {
                return ((string)(this["C0070_TELUGU_FRACTION_DIGIT_ONE_FOR_EVEN_POWERS_OF_FOUR"]));
            }
            set {
                this["C0070_TELUGU_FRACTION_DIGIT_ONE_FOR_EVEN_POWERS_OF_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2/4e")]
        public string C0080_TELUGU_FRACTION_DIGIT_TWO_FOR_EVEN_POWERS_OF_FOUR {
            get {
                return ((string)(this["C0080_TELUGU_FRACTION_DIGIT_TWO_FOR_EVEN_POWERS_OF_FOUR"]));
            }
            set {
                this["C0080_TELUGU_FRACTION_DIGIT_TWO_FOR_EVEN_POWERS_OF_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3/4e")]
        public string C0090_TELUGU_FRACTION_DIGIT_THREE_FOR_EVEN_POWERS_OF_FOUR {
            get {
                return ((string)(this["C0090_TELUGU_FRACTION_DIGIT_THREE_FOR_EVEN_POWERS_OF_FOUR"]));
            }
            set {
                this["C0090_TELUGU_FRACTION_DIGIT_THREE_FOR_EVEN_POWERS_OF_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".t")]
        public string C0100_TELUGU_SIGN_TUUMU {
            get {
                return ((string)(this["C0100_TELUGU_SIGN_TUUMU"]));
            }
            set {
                this["C0100_TELUGU_SIGN_TUUMU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string D0010_TAMIL_NUMBER_TEN {
            get {
                return ((string)(this["D0010_TAMIL_NUMBER_TEN"]));
            }
            set {
                this["D0010_TAMIL_NUMBER_TEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string D0020_TAMIL_NUMBER_ONE_HUNDRED {
            get {
                return ((string)(this["D0020_TAMIL_NUMBER_ONE_HUNDRED"]));
            }
            set {
                this["D0020_TAMIL_NUMBER_ONE_HUNDRED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string D0030_TAMIL_NUMBER_ONE_THOUSAND {
            get {
                return ((string)(this["D0030_TAMIL_NUMBER_ONE_THOUSAND"]));
            }
            set {
                this["D0030_TAMIL_NUMBER_ONE_THOUSAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("day")]
        public string D0040_TAMIL_DAY_SIGN {
            get {
                return ((string)(this["D0040_TAMIL_DAY_SIGN"]));
            }
            set {
                this["D0040_TAMIL_DAY_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mon")]
        public string D0050_TAMIL_MONTH_SIGN {
            get {
                return ((string)(this["D0050_TAMIL_MONTH_SIGN"]));
            }
            set {
                this["D0050_TAMIL_MONTH_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yr")]
        public string D0060_TAMIL_YEAR_SIGN {
            get {
                return ((string)(this["D0060_TAMIL_YEAR_SIGN"]));
            }
            set {
                this["D0060_TAMIL_YEAR_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DB")]
        public string D0070_TAMIL_DEBIT_SIGN {
            get {
                return ((string)(this["D0070_TAMIL_DEBIT_SIGN"]));
            }
            set {
                this["D0070_TAMIL_DEBIT_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CR")]
        public string D0080_TAMIL_CREDIT_SIGN {
            get {
                return ((string)(this["D0080_TAMIL_CREDIT_SIGN"]));
            }
            set {
                this["D0080_TAMIL_CREDIT_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@^")]
        public string D0090_TAMIL_AS_ABOVE_SIGN {
            get {
                return ((string)(this["D0090_TAMIL_AS_ABOVE_SIGN"]));
            }
            set {
                this["D0090_TAMIL_AS_ABOVE_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$")]
        public string D0100_TAMIL_RUPEE_SIGN {
            get {
                return ((string)(this["D0100_TAMIL_RUPEE_SIGN"]));
            }
            set {
                this["D0100_TAMIL_RUPEE_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
        public string D0110_TAMIL_NUMBER_SIGN {
            get {
                return ((string)(this["D0110_TAMIL_NUMBER_SIGN"]));
            }
            set {
                this["D0110_TAMIL_NUMBER_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f")]
        public string E0010_KANNADA_LETTER_FA {
            get {
                return ((string)(this["E0010_KANNADA_LETTER_FA"]));
            }
            set {
                this["E0010_KANNADA_LETTER_FA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".j")]
        public string E0020_KANNADA_SIGN_JIHVAMULIYA {
            get {
                return ((string)(this["E0020_KANNADA_SIGN_JIHVAMULIYA"]));
            }
            set {
                this["E0020_KANNADA_SIGN_JIHVAMULIYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".u")]
        public string E0030_KANNADA_SIGN_UPADHMANIYA {
            get {
                return ((string)(this["E0030_KANNADA_SIGN_UPADHMANIYA"]));
            }
            set {
                this["E0030_KANNADA_SIGN_UPADHMANIYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string F0010_MALAYALAM_NUMBER_TEN {
            get {
                return ((string)(this["F0010_MALAYALAM_NUMBER_TEN"]));
            }
            set {
                this["F0010_MALAYALAM_NUMBER_TEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string F0020_MALAYALAM_NUMBER_ONE_HUNDRED {
            get {
                return ((string)(this["F0020_MALAYALAM_NUMBER_ONE_HUNDRED"]));
            }
            set {
                this["F0020_MALAYALAM_NUMBER_ONE_HUNDRED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public string F0030_MALAYALAM_NUMBER_ONE_THOUSAND {
            get {
                return ((string)(this["F0030_MALAYALAM_NUMBER_ONE_THOUSAND"]));
            }
            set {
                this["F0030_MALAYALAM_NUMBER_ONE_THOUSAND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/4")]
        public string F0040_MALAYALAM_FRACTION_ONE_QUARTER {
            get {
                return ((string)(this["F0040_MALAYALAM_FRACTION_ONE_QUARTER"]));
            }
            set {
                this["F0040_MALAYALAM_FRACTION_ONE_QUARTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1/2")]
        public string F0050_MALAYALAM_FRACTION_ONE_HALF {
            get {
                return ((string)(this["F0050_MALAYALAM_FRACTION_ONE_HALF"]));
            }
            set {
                this["F0050_MALAYALAM_FRACTION_ONE_HALF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3/4")]
        public string F0060_MALAYALAM_FRACTION_THREE_QUARTERS {
            get {
                return ((string)(this["F0060_MALAYALAM_FRACTION_THREE_QUARTERS"]));
            }
            set {
                this["F0060_MALAYALAM_FRACTION_THREE_QUARTERS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("date")]
        public string F0070_MALAYALAM_DATE_MARK {
            get {
                return ((string)(this["F0070_MALAYALAM_DATE_MARK"]));
            }
            set {
                this["F0070_MALAYALAM_DATE_MARK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$")]
        public string G0010_GUJARATI_RUPEE_SIGN {
            get {
                return ((string)(this["G0010_GUJARATI_RUPEE_SIGN"]));
            }
            set {
                this["G0010_GUJARATI_RUPEE_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string H0010_ORIYA_LETTER_RRA {
            get {
                return ((string)(this["H0010_ORIYA_LETTER_RRA"]));
            }
            set {
                this["H0010_ORIYA_LETTER_RRA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rh")]
        public string H0020_ORIYA_LETTER_RHA {
            get {
                return ((string)(this["H0020_ORIYA_LETTER_RHA"]));
            }
            set {
                this["H0020_ORIYA_LETTER_RHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string H0030_ORIYA_LETTER_YYA {
            get {
                return ((string)(this["H0030_ORIYA_LETTER_YYA"]));
            }
            set {
                this["H0030_ORIYA_LETTER_YYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".i")]
        public string H0040_ORIYA_ISSHAR {
            get {
                return ((string)(this["H0040_ORIYA_ISSHAR"]));
            }
            set {
                this["H0040_ORIYA_ISSHAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public string H0050_ORIYA_LETTER_WA {
            get {
                return ((string)(this["H0050_ORIYA_LETTER_WA"]));
            }
            set {
                this["H0050_ORIYA_LETTER_WA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("K")]
        public string I0010_GURMUKHI_LETTER_KHHA {
            get {
                return ((string)(this["I0010_GURMUKHI_LETTER_KHHA"]));
            }
            set {
                this["I0010_GURMUKHI_LETTER_KHHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string I0020_GURMUKHI_LETTER_GHHA {
            get {
                return ((string)(this["I0020_GURMUKHI_LETTER_GHHA"]));
            }
            set {
                this["I0020_GURMUKHI_LETTER_GHHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J,z")]
        public string I0030_GURMUKHI_LETTER_ZA {
            get {
                return ((string)(this["I0030_GURMUKHI_LETTER_ZA"]));
            }
            set {
                this["I0030_GURMUKHI_LETTER_ZA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string I0040_GURMUKHI_LETTER_RRA {
            get {
                return ((string)(this["I0040_GURMUKHI_LETTER_RRA"]));
            }
            set {
                this["I0040_GURMUKHI_LETTER_RRA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f")]
        public string I0050_GURMUKHI_LETTER_FA {
            get {
                return ((string)(this["I0050_GURMUKHI_LETTER_FA"]));
            }
            set {
                this["I0050_GURMUKHI_LETTER_FA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".p")]
        public string I0060_GURMUKHI_TIPPI {
            get {
                return ((string)(this["I0060_GURMUKHI_TIPPI"]));
            }
            set {
                this["I0060_GURMUKHI_TIPPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".d")]
        public string I0070_GURMUKHI_ADDAK {
            get {
                return ((string)(this["I0070_GURMUKHI_ADDAK"]));
            }
            set {
                this["I0070_GURMUKHI_ADDAK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".ir")]
        public string I0080_GURMUKHI_IRI {
            get {
                return ((string)(this["I0080_GURMUKHI_IRI"]));
            }
            set {
                this["I0080_GURMUKHI_IRI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".r")]
        public string I0090_GURMUKHI_URA {
            get {
                return ((string)(this["I0090_GURMUKHI_URA"]));
            }
            set {
                this["I0090_GURMUKHI_URA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("onkar")]
        public string I0100_GURMUKHI_EK_ONKAR {
            get {
                return ((string)(this["I0100_GURMUKHI_EK_ONKAR"]));
            }
            set {
                this["I0100_GURMUKHI_EK_ONKAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string I0110_GURMUKHI_SIGN_YAKASH {
            get {
                return ((string)(this["I0110_GURMUKHI_SIGN_YAKASH"]));
            }
            set {
                this["I0110_GURMUKHI_SIGN_YAKASH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".T")]
        public string J0010_BENGALI_SIGN_KHANDA_TA {
            get {
                return ((string)(this["J0010_BENGALI_SIGN_KHANDA_TA"]));
            }
            set {
                this["J0010_BENGALI_SIGN_KHANDA_TA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R")]
        public string J0020_BENGALI_LETTER_RRA {
            get {
                return ((string)(this["J0020_BENGALI_LETTER_RRA"]));
            }
            set {
                this["J0020_BENGALI_LETTER_RRA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rh")]
        public string J0030_BENGALI_LETTER_RHA {
            get {
                return ((string)(this["J0030_BENGALI_LETTER_RHA"]));
            }
            set {
                this["J0030_BENGALI_LETTER_RHA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y")]
        public string J0040_BENGALI_LETTER_YYA {
            get {
                return ((string)(this["J0040_BENGALI_LETTER_YYA"]));
            }
            set {
                this["J0040_BENGALI_LETTER_YYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R.d")]
        public string J0050_BENGALI_LETTER_RA_WITH_MIDDLE_DIAGONAL {
            get {
                return ((string)(this["J0050_BENGALI_LETTER_RA_WITH_MIDDLE_DIAGONAL"]));
            }
            set {
                this["J0050_BENGALI_LETTER_RA_WITH_MIDDLE_DIAGONAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("R.l")]
        public string J0060_BENGALI_LETTER_RA_WITH_LOWER_DIAGONAL {
            get {
                return ((string)(this["J0060_BENGALI_LETTER_RA_WITH_LOWER_DIAGONAL"]));
            }
            set {
                this["J0060_BENGALI_LETTER_RA_WITH_LOWER_DIAGONAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".$")]
        public string J0070_BENGALI_RUPEE_MARK {
            get {
                return ((string)(this["J0070_BENGALI_RUPEE_MARK"]));
            }
            set {
                this["J0070_BENGALI_RUPEE_MARK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$")]
        public string J0080_BENGALI_RUPEE_SIGN {
            get {
                return ((string)(this["J0080_BENGALI_RUPEE_SIGN"]));
            }
            set {
                this["J0080_BENGALI_RUPEE_SIGN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$1")]
        public string J0090_BENGALI_CURRENCY_NUMERATOR_ONE {
            get {
                return ((string)(this["J0090_BENGALI_CURRENCY_NUMERATOR_ONE"]));
            }
            set {
                this["J0090_BENGALI_CURRENCY_NUMERATOR_ONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$2")]
        public string J0100_BENGALI_CURRENCY_NUMERATOR_TWO {
            get {
                return ((string)(this["J0100_BENGALI_CURRENCY_NUMERATOR_TWO"]));
            }
            set {
                this["J0100_BENGALI_CURRENCY_NUMERATOR_TWO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$3")]
        public string J0110_BENGALI_CURRENCY_NUMERATOR_THREE {
            get {
                return ((string)(this["J0110_BENGALI_CURRENCY_NUMERATOR_THREE"]));
            }
            set {
                this["J0110_BENGALI_CURRENCY_NUMERATOR_THREE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$4")]
        public string J0120_BENGALI_CURRENCY_NUMERATOR_FOUR {
            get {
                return ((string)(this["J0120_BENGALI_CURRENCY_NUMERATOR_FOUR"]));
            }
            set {
                this["J0120_BENGALI_CURRENCY_NUMERATOR_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$-1")]
        public string J0130_BENGALI_CURRENCY_NUMERATOR_ONE_LESS_THAN_THE_DENOMINATOR {
            get {
                return ((string)(this["J0130_BENGALI_CURRENCY_NUMERATOR_ONE_LESS_THAN_THE_DENOMINATOR"]));
            }
            set {
                this["J0130_BENGALI_CURRENCY_NUMERATOR_ONE_LESS_THAN_THE_DENOMINATOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$d16")]
        public string J0140_BENGALI_CURRENCY_DENOMINATOR_SIXTEEN {
            get {
                return ((string)(this["J0140_BENGALI_CURRENCY_DENOMINATOR_SIXTEEN"]));
            }
            set {
                this["J0140_BENGALI_CURRENCY_DENOMINATOR_SIXTEEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".i")]
        public string J0150_BENGALI_ISSHAR {
            get {
                return ((string)(this["J0150_BENGALI_ISSHAR"]));
            }
            set {
                this["J0150_BENGALI_ISSHAR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zwj")]
        public string X010_ZWJ {
            get {
                return ((string)(this["X010_ZWJ"]));
            }
            set {
                this["X010_ZWJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zwnj")]
        public string X020_ZWNJ {
            get {
                return ((string)(this["X020_ZWNJ"]));
            }
            set {
                this["X020_ZWNJ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^.")]
        public string X030_DOT_ABOVE {
            get {
                return ((string)(this["X030_DOT_ABOVE"]));
            }
            set {
                this["X030_DOT_ABOVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_.")]
        public string X040_DOT_BELOW {
            get {
                return ((string)(this["X040_DOT_BELOW"]));
            }
            set {
                this["X040_DOT_BELOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FF")]
        public string X050_FORM_FEED {
            get {
                return ((string)(this["X050_FORM_FEED"]));
            }
            set {
                this["X050_FORM_FEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GY,j~n")]
        public string A0325_CONJUNCT_GYA {
            get {
                return ((string)(this["A0325_CONJUNCT_GYA"]));
            }
            set {
                this["A0325_CONJUNCT_GYA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^R")]
        public string A0535_LETTER_EYELASH_RA {
            get {
                return ((string)(this["A0535_LETTER_EYELASH_RA"]));
            }
            set {
                this["A0535_LETTER_EYELASH_RA"] = value;
            }
        }
    }
}
